from typing import Protocol, Optional

from src.main.api.models.base_model import BaseModel


class CrudEndpointInterface(Protocol):
    def post(self, model: BaseModel): ...
    def get(self, id: Optional[int] = None): ...
    def update(self, model: BaseModel, id: Optional[int] = None): ...
    def delete(self, id: int): ...